#!/bin/bash

# -----------------------------------------------------------------------------
# Run unit tests before pushing.
#
# To skip running tests, set the environment variable SKIP_TESTS to "true":
#   Example: SKIP_TESTS=true git push
# -----------------------------------------------------------------------------
if [ "$SKIP_TESTS" != "true" ]; then
	bun run test
fi
